# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23144f0fe5da73d252ff404ab878d9213394770cbf144c984df193ab7c897a01de368025bd94c1e96293bdd9dac39163797b13bbf28cc811fd123d0db378f212

test:
  secret_key_base: f65fbed1d36c9cc19026bcb0cb3ddafe16d8277a6f6dc397f40cb17ea4c098114929c552856bdad82b5848b2a9a41ea689bf72dac8127994fcf28bb7540dbd69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
